name: Plugin tags Api CI

on:
  push:
    branches:
      - dev
      - staging
      - node-v18
    paths:
      - 'packages/api-utils/**'
      - 'packages/api-plugin-template.erxes/**'
      - 'packages/plugin-tags-api/**'
      - '.github/workflows/plugin-tags-api.yaml'
  pull_request:
    branches:
      - dev
      - staging
    paths:
      - 'packages/api-utils/**'
      - 'packages/api-plugin-template.erxes/**'
      - 'packages/plugin-tags-api/**'
      - '.github/workflows/plugin-tags-api.yaml'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: node:18.17.0-bookworm-slim
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.17.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-plugin-tags-api-${{ hashFiles('yarn.lock', 'plugin-tags-api/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-plugin-tags-api-
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          cp -r builder dist
          cd dist
          yarn install
          yarn build plugin tags
          cd plugin-tags-api/.erxes
          cd dist/main/.erxes/src
      - name: Create tarball of build artifact
        run: |
          tar -cf dist.tar ./dist
      - name: Save build artifact for the next job
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist.tar
  docker-push:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
      - name: Extract build artifact
        run: |
          tar -xf dist.tar ./dist/
      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/node-v18')
        run: |
          cd dist/plugin-tags-api/.erxes
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t erxes/plugin-tags-api:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/plugin-tags-api:${GITHUB_REF#refs/heads/}
